export const Endpoints = {
    registerEmployee:'registerEmployee',
    registerCompany:'registerCompany',
    login:'login',
    forget_password:'password/reseter',
    request_forget_password:'password/email',
    provider_cards:"misc/cards",
    save_logout:"misc/save_logout",
    sendReport:"misc/sendReport",
    employee:{
        profile:'employees/profile',
        updateProfile:'employees/updateProfile',
        suggested_courses:'employees/suggested_courses',
        nominations:'employees/nominations',
        accept_nomination:'employees/accept_nomination',
        accept_course_contract:'employees/accept_course_contract',
        tasks:'employees/tasks',
        payments:'employees/payments',
        makePayment:'employees/makePayment',
        update_payment:'employees/payments',
        jobs:'employees/jobs',
        attach_insurance_file:'employees/attach_insurance_file',
        resigns:'employees/resigns',
        start_task:'employees/start_task',
        finish_task:'employees/finish_task',
        attendance:'employees/attendances',
    },
    provider:{
        profile:'provider/profile',
        users:'users',
        permissions:'permissions',
        roles:'roles',
        PermissionByKey:'permissions/PermissionByKey',
        employees:'provider/employees',
        courses:'provider/courses',
        jobs:'provider/jobs',
        jobRequests:'provider/JobRequests',
        tasks:'provider/tasks',
        assign_tasks: 'provider/jobs/assign_tasks',
        search_nominants:'provider/JobRequests/search_nominants',
        companies:'provider/companies',
        pending_companies:'provider/pending_companies',
        banned_companies:'provider/banned_companies',
        banned_employees:'provider/banned_employees',
        candidates:'provider/candidates',
        pending_candidates:'provider/pending_candidates',
        banned_candidates:'provider/banned_candidates',
        insurances:'provider/insurances',
        resigns:'provider/resigns',
        approve_resign:'provider/approve_resign',
        updateSettings:'provider/updateSettings',
        settings:'provider/settings',
        attendance:'provider/attendances',
        filter_data:'reports/filter_data',
        reports:'reports',
        custom:'reports/custom',
        registerEmployee:'provider/registerEmployee',
        registerCompany:'provider/registerCompany',
        add_task_attachments:'provider/add_task_attachments',
        assign_candidate_to_company:'provider/assign_candidate_to_company',
        prepare_remote_reports:'provider/prepare_remote_reports',
    },
    company:{
        emp_requests:'companies/emp_requests',
        list_emp_request_nominations:'companies/list_emp_request_nominations',
        admit_emp_request_candidate: 'companies/admit_emp_request_candidate',
        profile: 'companies/profile',
        updateProfile:'companies/updateProfile',
        list_employees: 'companies/list_employees',
        emp_task: 'companies/emp_task',
        assign_emp_task:'companies/assign_emp_task',
        attach_insurance_file: 'companies/attach_insurance_file',
        payments:'companies/payments',
        makePayment:'companies/makePayment',
        resigns:'companies/resigns',
        attendance:'companies/attendances',
        delete_task:'companies/emp_task',
        filter_data:'companies/filter_data',
        reports:'companies/reports',
    },
    enums:'enums',
    // banks:'banks',
    misc:{
        banks:'banks',
        emp_tasks:'misc/emp_tasks',
        notifications:'misc/notifications',
        read_notifications:'misc/notifyRead',
        settings:'provider/settings'
    },
    messages:{
        inbox: 'messages/inbox',
        sent:'messages/sent',
        messages:'messages',
    }
}